/**
 * MCP Tool Browser — Extended domain groups
 *
 * Continuation of tool-catalog.ts for domains beyond the core set.
 */

import type { ToolDef, DomainGroup } from "./types";
import { PARAM_SCHEMAS } from "./param-schemas";

function t(name: string, description: string, domain: string): ToolDef {
  return { name, description, domain, params: PARAM_SCHEMAS[name] };
}

export const EXTENDED_DOMAINS: DomainGroup[] = [
  {
    domain: "compendious",
    label: "Compendious",
    description: "Text density analysis and compression",
    tools: [
      t("compendious_score_text", "Score information density", "compendious"),
      t(
        "compendious_compress_text",
        "Compress preserving meaning",
        "compendious",
      ),
      t("compendious_compare_texts", "Compare text densities", "compendious"),
      t(
        "compendious_analyze_patterns",
        "Analyze writing patterns",
        "compendious",
      ),
      t(
        "compendious_get_domain_target",
        "Get domain target density",
        "compendious",
      ),
    ],
  },
  {
    domain: "algovigilance",
    label: "Algovigilance",
    description: "Algorithmic vigilance monitoring",
    tools: [
      t("algovigil_status", "System status", "algovigilance"),
      t("algovigil_triage_decay", "Triage decay analysis", "algovigilance"),
      t("algovigil_triage_queue", "Current triage queue", "algovigilance"),
    ],
  },
  {
    domain: "regulatory",
    label: "Regulatory & Compliance",
    description: "Regulatory primitives, compliance, and SEC filings",
    tools: [
      t(
        "regulatory_primitives_extract",
        "Extract regulatory primitives",
        "regulatory",
      ),
      t("regulatory_primitives_audit", "Audit compliance", "regulatory"),
      t("regulatory_primitives_compare", "Compare frameworks", "regulatory"),
      t("primitive_validate", "Validate a primitive", "regulatory"),
      t("primitive_cite", "Cite primitive provenance", "regulatory"),
      t("primitive_validate_batch", "Batch validation", "regulatory"),
      t("primitive_validation_tiers", "Validation tier lookup", "regulatory"),
      t("compliance_catalog_ich", "ICH compliance catalog", "regulatory"),
      t("compliance_sec_filings", "SEC filing analysis", "regulatory"),
      t("compliance_sec_pharma", "SEC pharma analysis", "regulatory"),
    ],
  },
  {
    domain: "signal",
    label: "Signal Detection",
    description: "Signal detection and thresholds",
    tools: [
      t("signal_detect", "Detect signal", "signal"),
      t("signal_batch", "Batch detection", "signal"),
      t("signal_thresholds", "Get thresholds", "signal"),
    ],
  },
  {
    domain: "foundry",
    label: "Foundry & Forge",
    description: "Artifact validation, rendering, and content scaffolding",
    tools: [
      t("foundry_validate_artifact", "Validate artifact", "foundry"),
      t("foundry_cascade_validate", "Cascade validation", "foundry"),
      t("foundry_render_intelligence", "Render intelligence", "foundry"),
      t("foundry_vdag_order", "VDAG ordering", "foundry"),
      t("foundry_infer", "Foundry inference", "foundry"),
      t("forge_extract", "Extract IR", "foundry"),
      t("forge_validate", "Validate content", "foundry"),
      t("forge_scaffold", "Scaffold content", "foundry"),
      t("forge_schema", "Get schema", "foundry"),
    ],
  },
  {
    domain: "trial",
    label: "TRIAL Framework",
    description: "Clinical trial methodology tools",
    tools: [
      t("trial_protocol_register", "Register protocol", "trial"),
      t("trial_power_analysis", "Power analysis", "trial"),
      t("trial_randomize", "Randomization", "trial"),
      t("trial_blind_verify", "Blinding verification", "trial"),
      t("trial_interim_analyze", "Interim analysis", "trial"),
      t("trial_safety_check", "Safety monitoring", "trial"),
      t("trial_endpoint_evaluate", "Endpoint evaluation", "trial"),
      t("trial_multiplicity_adjust", "Multiplicity adjustment", "trial"),
      t("trial_adapt_decide", "Adaptive decision", "trial"),
      t("trial_report_generate", "Report generation", "trial"),
    ],
  },
  {
    domain: "drift",
    label: "Drift & Observability",
    description: "Distribution drift, rank fusion, and observability",
    tools: [
      t("drift_ks_test", "KS test", "drift"),
      t("drift_psi", "Population Stability Index", "drift"),
      t("drift_jsd", "Jensen-Shannon divergence", "drift"),
      t("drift_detect", "Auto-detect drift", "drift"),
      t("rank_fusion_rrf", "Reciprocal Rank Fusion", "drift"),
      t("rank_fusion_hybrid", "Hybrid rank fusion", "drift"),
      t("rank_fusion_borda", "Borda count", "drift"),
      t("observability_query", "Query metrics", "drift"),
      t("observability_freshness", "Data freshness", "drift"),
    ],
  },
  {
    domain: "observatory",
    label: "Observatory",
    description: "Career, learning, graph layout, personalization",
    tools: [
      t("career_transitions", "Career transitions", "observatory"),
      t("learning_dag_resolve", "Learning DAG resolution", "observatory"),
      t("graph_layout_converge", "Force-directed layout", "observatory"),
      t("observatory_personalize_detect", "Detect preferences", "observatory"),
      t("observatory_personalize_get", "Get personalization", "observatory"),
      t("observatory_personalize_set", "Set personalization", "observatory"),
      t("observatory_personalize_validate", "Validate settings", "observatory"),
    ],
  },
  {
    domain: "stoichiometry",
    label: "Stoichiometry",
    description: "Balanced primitive equations and concept encoding",
    tools: [
      t("stoichiometry_encode", "Encode as equation", "stoichiometry"),
      t("stoichiometry_decode", "Decode (Jeopardy)", "stoichiometry"),
      t("stoichiometry_sisters", "Find sisters", "stoichiometry"),
      t("stoichiometry_mass_state", "Mass-state thermo", "stoichiometry"),
      t("stoichiometry_dictionary", "Dictionary", "stoichiometry"),
      t("stoichiometry_is_balanced", "Check balance", "stoichiometry"),
      t("stoichiometry_prove", "Prove conservation", "stoichiometry"),
      t("stoichiometry_is_isomer", "Check isomer", "stoichiometry"),
    ],
  },
  {
    domain: "chemivigilance",
    label: "Chemivigilance",
    description: "Molecular analysis, structural alerts, toxicity",
    tools: [
      t("chem_parse_smiles", "Parse SMILES", "chemivigilance"),
      t("chem_descriptors", "Molecular descriptors", "chemivigilance"),
      t("chem_fingerprint", "Fingerprint generation", "chemivigilance"),
      t("chem_similarity", "Molecular similarity", "chemivigilance"),
      t("chem_structural_alerts", "Structural alerts", "chemivigilance"),
      t("chem_predict_toxicity", "QSAR toxicity", "chemivigilance"),
      t("chem_predict_metabolites", "Metabolite prediction", "chemivigilance"),
      t("chem_predict_degradants", "Degradant prediction", "chemivigilance"),
      t("chem_safety_brief", "Safety briefing", "chemivigilance"),
      t("chem_substructure", "Substructure search", "chemivigilance"),
      t("chem_watchlist", "Watchlist check", "chemivigilance"),
      t("chem_alert_library", "Alert library", "chemivigilance"),
      t("chem_ring_scan", "Ring system analysis", "chemivigilance"),
      t("chem_aromaticity", "Aromaticity detection", "chemivigilance"),
      t("chem_molecular_formula", "Molecular formula", "chemivigilance"),
    ],
  },
  {
    domain: "nmd",
    label: "NMD Surveillance",
    description: "Anti-hallucination pipeline",
    tools: [
      t("nmd_check", "NMD check", "nmd"),
      t("nmd_upf_evaluate", "UPF evaluation", "nmd"),
      t("nmd_smg_process", "SMG processing", "nmd"),
      t("nmd_adaptive_stats", "Adaptive statistics", "nmd"),
      t("nmd_thymic_status", "Thymic status", "nmd"),
      t("nmd_status", "NMD system status", "nmd"),
    ],
  },
  {
    domain: "cloud",
    label: "Cloud Intelligence",
    description: "Cloud taxonomy, transfer, and architecture",
    tools: [
      t("cloud_primitive_composition", "Primitive composition", "cloud"),
      t("cloud_transfer_confidence", "Transfer confidence", "cloud"),
      t("cloud_tier_classify", "Tier classification", "cloud"),
      t("cloud_compare_types", "Compare types", "cloud"),
      t("cloud_reverse_synthesize", "Reverse synthesis", "cloud"),
      t("cloud_list_types", "List types", "cloud"),
      t("cloud_molecular_weight", "Molecular weight", "cloud"),
      t("cloud_dominant_shift", "Dominant shift", "cloud"),
      t("cloud_capacity_project", "Capacity projection", "cloud"),
      t("cloud_supervisor_health", "Supervisor health", "cloud"),
      t("cloud_reverse_transfer", "Reverse transfer", "cloud"),
      t("cloud_transfer_chain", "Transfer chain", "cloud"),
      t("cloud_architecture_advisor", "Architecture advisor", "cloud"),
      t("cloud_anomaly_detect", "Anomaly detection", "cloud"),
      t("cloud_transfer_matrix", "Transfer matrix", "cloud"),
      t("cloud_infra_status", "Infra status", "cloud"),
      t("cloud_infra_map", "Infra map", "cloud"),
    ],
  },
  {
    domain: "lex_primitiva",
    label: "Lex Primitiva",
    description: "Type taxonomy and primitive composition",
    tools: [
      t("lex_primitiva_list", "List all primitives", "lex_primitiva"),
      t("lex_primitiva_get", "Get specific primitive", "lex_primitiva"),
      t("lex_primitiva_tier", "Tier classification", "lex_primitiva"),
      t("lex_primitiva_composition", "Type composition", "lex_primitiva"),
      t(
        "lex_primitiva_reverse_compose",
        "Reverse composition",
        "lex_primitiva",
      ),
      t("lex_primitiva_reverse_lookup", "Reverse lookup", "lex_primitiva"),
      t("lex_primitiva_molecular_weight", "Molecular weight", "lex_primitiva"),
      t("lex_primitiva_dominant_shift", "Dominant shift", "lex_primitiva"),
      t("lex_primitiva_state_mode", "State mode", "lex_primitiva"),
      t("lex_primitiva_audit", "Audit", "lex_primitiva"),
      t("lex_primitiva_synth", "Synthesize type", "lex_primitiva"),
    ],
  },
  {
    domain: "fda",
    label: "FDA & FHIR",
    description: "FDA credibility assessment and FHIR clinical data",
    tools: [
      t("fda_define_cou", "Define context of use", "fda"),
      t("fda_assess_risk", "Assess risk", "fda"),
      t("fda_create_plan", "Create plan", "fda"),
      t("fda_validate_evidence", "Validate evidence", "fda"),
      t("fda_decide_adequacy", "Decide adequacy", "fda"),
      t("fda_calculate_score", "Calculate score", "fda"),
      t("fda_metrics_summary", "Metrics summary", "fda"),
      t("fda_evidence_distribution", "Evidence distribution", "fda"),
      t("fda_risk_distribution", "Risk distribution", "fda"),
      t("fda_drift_trend", "Drift trend", "fda"),
      t("fda_rating_thresholds", "Rating thresholds", "fda"),
      t("fda_guidance_status", "Guidance status", "fda"),
      t("fhir_adverse_event_to_signal", "FHIR AE to signal", "fda"),
      t("fhir_batch_to_signals", "Batch FHIR to signals", "fda"),
      t("fhir_parse_bundle", "Parse FHIR bundle", "fda"),
      t("fhir_validate_resource", "Validate resource", "fda"),
    ],
  },
  {
    domain: "misc_science",
    label: "Molecular & Pharma",
    description: "Molecular biology, pharma R&D, polymers, combinatorics",
    tools: [
      t("molecular_translate_codon", "Translate codon", "misc_science"),
      t("molecular_translate_mrna", "Translate mRNA", "misc_science"),
      t("molecular_central_dogma", "Central dogma", "misc_science"),
      t("molecular_adme_phase", "ADME phase", "misc_science"),
      t("mw_compute", "Molecular weight", "misc_science"),
      t("mw_periodic_table", "Periodic table", "misc_science"),
      t("mw_compare", "Compare MW", "misc_science"),
      t("mw_predict_transfer", "Predict transfer", "misc_science"),
      t("pharma_taxonomy_summary", "Pharma taxonomy", "misc_science"),
      t("pharma_lookup_transfer", "Transfer lookup", "misc_science"),
      t("pharma_transfer_matrix", "Transfer matrix", "misc_science"),
      t("pharma_strongest_transfers", "Strongest transfers", "misc_science"),
      t("pharma_weakest_transfers", "Weakest transfers", "misc_science"),
      t("pharma_symbol_coverage", "Symbol coverage", "misc_science"),
      t("pharma_pipeline_stage", "Pipeline stage", "misc_science"),
      t("pharma_classify_generators", "Generator class", "misc_science"),
      t("polymer_compose", "Compose polymer", "misc_science"),
      t("polymer_validate", "Validate polymer", "misc_science"),
      t("polymer_analyze", "Analyze polymer", "misc_science"),
      t("comb_catalan", "Catalan number", "misc_science"),
      t("comb_catalan_table", "Catalan table", "misc_science"),
      t("comb_cycle_decomposition", "Cycle decomposition", "misc_science"),
      t("comb_min_transpositions", "Min transpositions", "misc_science"),
      t("comb_derangement", "Derangement count", "misc_science"),
      t("comb_derangement_probability", "Derangement prob", "misc_science"),
      t("comb_grid_paths", "Grid paths", "misc_science"),
      t("comb_binomial", "Binomial coefficient", "misc_science"),
      t("comb_multinomial", "Multinomial coefficient", "misc_science"),
      t("comb_josephus", "Josephus problem", "misc_science"),
      t("comb_elimination_order", "Elimination order", "misc_science"),
      t("comb_linear_extensions", "Linear extensions", "misc_science"),
      t("aggregate_fold", "Fold/reduce", "misc_science"),
      t("aggregate_tree_fold", "Tree fold", "misc_science"),
      t("aggregate_rank", "Rank aggregation", "misc_science"),
      t("aggregate_percentile", "Percentile", "misc_science"),
      t("aggregate_outliers", "Outlier detection", "misc_science"),
    ],
  },
  {
    domain: "pv_advanced",
    label: "PV Advanced",
    description: "Axioms, DSL, and embeddings",
    tools: [
      t("pv_axioms_ksb_lookup", "KSB lookup", "pv_advanced"),
      t("pv_axioms_regulation_search", "Regulation search", "pv_advanced"),
      t("pv_axioms_traceability_chain", "Traceability chain", "pv_advanced"),
      t("pv_axioms_domain_dashboard", "Domain dashboard", "pv_advanced"),
      t("pv_axioms_query", "Axioms query", "pv_advanced"),
      t("pvdsl_compile", "Compile PVDSL", "pv_advanced"),
      t("pvdsl_execute", "Execute PVDSL", "pv_advanced"),
      t("pvdsl_eval", "Evaluate PVDSL", "pv_advanced"),
      t("pvdsl_functions", "PVDSL functions", "pv_advanced"),
      t("pv_embedding_similarity", "Embedding similarity", "pv_advanced"),
      t("pv_embedding_get", "Get embedding", "pv_advanced"),
      t("pv_embedding_stats", "Embedding stats", "pv_advanced"),
    ],
  },
  {
    domain: "safety",
    label: "Safety & Security",
    description: "ToV grounded safety, security posture, reason",
    tools: [
      t("tov_grounded_signal_strength", "ToV signal strength", "safety"),
      t("tov_grounded_safety_margin", "ToV safety margin", "safety"),
      t("tov_grounded_stability_shell", "Stability shell", "safety"),
      t("tov_grounded_harm_type", "Harm type", "safety"),
      t("tov_grounded_meta_vigilance", "Meta-vigilance", "safety"),
      t("tov_grounded_eka_intelligence", "Eka intelligence", "safety"),
      t("tov_grounded_magic_numbers", "Magic numbers", "safety"),
      t("security_posture_assess", "Posture assessment", "safety"),
      t("security_threat_readiness", "Threat readiness", "safety"),
      t("security_compliance_gap", "Compliance gap", "safety"),
      t("reason_infer", "Logical inference", "safety"),
      t("reason_counterfactual", "Counterfactual", "safety"),
    ],
  },
  {
    domain: "viz",
    label: "Visualization",
    description: "Observatory visualization (31 tools)",
    tools: [
      t("viz_stem_taxonomy", "STEM taxonomy viz", "viz"),
      t("viz_type_composition", "Type composition", "viz"),
      t("viz_method_loop", "Method loop", "viz"),
      t("viz_confidence_chain", "Confidence chain", "viz"),
      t("viz_bounds", "Bounds viz", "viz"),
      t("viz_dag", "DAG visualization", "viz"),
      t("viz_molecular_info", "Molecular info", "viz"),
      t("viz_surface_mesh", "Surface mesh", "viz"),
      t("viz_spectral_analysis", "Spectral analysis", "viz"),
      t("viz_community_detect", "Community detection", "viz"),
      t("viz_centrality", "Centrality viz", "viz"),
      t("viz_vdag_overlay", "VDAG overlay", "viz"),
      t("viz_antibody_structure", "Antibody structure", "viz"),
      t("viz_interaction_map", "Interaction map", "viz"),
      t("viz_projection", "Data projection", "viz"),
      t("viz_protein_structure", "Protein structure", "viz"),
      t("viz_topology_analysis", "Topology analysis", "viz"),
      t("viz_dynamics_step", "Dynamics step", "viz"),
      t("viz_force_field_energy", "Force field energy", "viz"),
      t("viz_gpu_layout", "GPU layout", "viz"),
      t("viz_hypergraph", "Hypergraph", "viz"),
      t("viz_lod_select", "LOD selection", "viz"),
      t("viz_minimize_energy", "Energy minimize", "viz"),
      t("viz_particle_preset", "Particle preset", "viz"),
      t("viz_ae_overlay", "AE overlay", "viz"),
      t("viz_coord_gen", "Coordinate gen", "viz"),
      t("viz_bipartite_layout", "Bipartite layout", "viz"),
      t("viz_manifold_sample", "Manifold sampling", "viz"),
      t("viz_string_modes", "String modes", "viz"),
      t("viz_render_pipeline", "Render pipeline", "viz"),
      t("viz_orbital_density", "Orbital density", "viz"),
    ],
  },
  {
    domain: "platform",
    label: "Platform & Telemetry",
    description:
      "Value mining, measure, visual, zeta, docs, telemetry, watchtower",
    tools: [
      t("value_signal_types", "Value signal types", "platform"),
      t("value_signal_detect", "Detect value signals", "platform"),
      t("value_baseline_create", "Create baseline", "platform"),
      t("value_pv_mapping", "Value-to-PV mapping", "platform"),
      t("measure_crate", "Measure crate", "platform"),
      t("measure_workspace", "Measure workspace", "platform"),
      t("measure_entropy", "Measure entropy", "platform"),
      t("measure_graph", "Measure graph", "platform"),
      t("measure_drift", "Measure drift", "platform"),
      t("measure_compare", "Compare measures", "platform"),
      t("measure_stats", "Measure stats", "platform"),
      t("quality_gradient", "Quality gradient", "platform"),
      t("visual_shape_classify", "Shape classify", "platform"),
      t("visual_color_analyze", "Color analyze", "platform"),
      t("visual_shape_list", "Shape list", "platform"),
      t("zeta_compute", "Zeta function", "platform"),
      t("zeta_find_zeros", "Find zeros", "platform"),
      t("zeta_verify_rh", "Verify RH", "platform"),
      t("zeta_embedded_zeros", "Embedded zeros", "platform"),
      t("zeta_lmfdb_parse", "LMFDB parse", "platform"),
      t("zeta_telescope_run", "Telescope run", "platform"),
      t("zeta_batch_run", "Batch run", "platform"),
      t("zeta_scaling_fit", "Scaling fit", "platform"),
      t("zeta_scaling_predict", "Scaling predict", "platform"),
      t("zeta_cayley", "Cayley graph", "platform"),
      t("zeta_operator_hunt", "Operator hunt", "platform"),
      t("zeta_operator_candidate", "Operator candidate", "platform"),
      t("zeta_gue_compare", "GUE compare", "platform"),
      t("docs_claude_list_pages", "List docs", "platform"),
      t("docs_claude_get_page", "Get doc page", "platform"),
      t("docs_claude_search_docs", "Search docs", "platform"),
      t("docs_claude_get_docs_index", "Docs index", "platform"),
      t("telemetry_sources_list", "Telemetry sources", "platform"),
      t("telemetry_source_analyze", "Analyze source", "platform"),
      t("telemetry_governance_crossref", "Governance xref", "platform"),
      t("telemetry_snapshot_evolution", "Snapshot evolution", "platform"),
      t("telemetry_intel_report", "Intel report", "platform"),
      t("telemetry_recent", "Recent telemetry", "platform"),
      t("watchtower_sessions_list", "Sessions list", "platform"),
      t("watchtower_active_sessions", "Active sessions", "platform"),
      t("watchtower_analyze", "Analyze session", "platform"),
      t("watchtower_telemetry_stats", "Telemetry stats", "platform"),
      t("watchtower_recent", "Recent data", "platform"),
      t("watchtower_symbol_audit", "Symbol audit", "platform"),
      t("watchtower_unified", "Unified analysis", "platform"),
    ],
  },
  {
    domain: "topology",
    label: "Topology",
    description: "Topological data analysis and graph computation",
    tools: [
      t("topo_vietoris_rips", "Vietoris-Rips complex", "topology"),
      t("topo_persistence", "Persistent homology", "topology"),
      t("topo_betti", "Betti numbers", "topology"),
      t("graph_centrality", "Graph centrality", "topology"),
      t("graph_components", "Connected components", "topology"),
      t("graph_shortest_path", "Shortest path", "topology"),
    ],
  },
];
