/**
 * MCP Tool Browser — Tool Catalog (core domains)
 *
 * Extracted from ALLOWED_TOOLS in nexcore-api/src/routes/mcp.rs.
 * Split across tool-catalog.ts (core) and tool-catalog-extended.ts (extended).
 */

import type { ToolDef, DomainGroup } from './types'
import { PARAM_SCHEMAS } from './param-schemas'
import { EXTENDED_DOMAINS } from './tool-catalog-extended'

function t(name: string, description: string, domain: string): ToolDef {
  return { name, description, domain, params: PARAM_SCHEMAS[name] }
}

const CORE_DOMAINS: DomainGroup[] = [
  {
    domain: 'foundation', label: 'Foundation',
    description: 'Core string, hash, graph, and fuzzy search operations',
    tools: [
      t('foundation_levenshtein', 'Levenshtein edit distance', 'foundation'),
      t('foundation_levenshtein_bounded', 'Bounded Levenshtein (early exit)', 'foundation'),
      t('foundation_fuzzy_search', 'Fuzzy text search across candidates', 'foundation'),
      t('foundation_sha256', 'SHA-256 hash of input string', 'foundation'),
      t('foundation_yaml_parse', 'Parse YAML/JSON with type safety', 'foundation'),
      t('foundation_graph_topsort', 'Topological sort of a DAG', 'foundation'),
      t('foundation_graph_levels', 'Level assignment in a DAG', 'foundation'),
      t('foundation_fsrs_review', 'FSRS spaced repetition scheduling', 'foundation'),
      t('foundation_concept_grep', 'Multi-variant concept search', 'foundation'),
      t('foundation_domain_distance', 'Semantic distance between domains', 'foundation'),
      t('foundation_spectral_overlap', 'Spectral overlap of distributions', 'foundation'),
      t('foundation_token_ratio', 'Token ratio analysis', 'foundation'),
      t('foundation_flywheel_velocity', 'Flywheel velocity computation', 'foundation'),
    ],
  },
  {
    domain: 'pv_signal', label: 'PV Signal Detection',
    description: 'Pharmacovigilance signal detection (PRR, ROR, IC, EBGM)',
    tools: [
      t('pv_signal_complete', 'Complete signal detection (all methods)', 'pv_signal'),
      t('pv_signal_prr', 'Proportional Reporting Ratio', 'pv_signal'),
      t('pv_signal_ror', 'Reporting Odds Ratio', 'pv_signal'),
      t('pv_signal_ic', 'Information Component (Bayesian)', 'pv_signal'),
      t('pv_signal_ebgm', 'Empirical Bayes Geometric Mean', 'pv_signal'),
      t('pv_chi_square', 'Chi-square test for signals', 'pv_signal'),
      t('pv_naranjo_quick', 'Naranjo causality assessment', 'pv_signal'),
      t('pv_who_umc_quick', 'WHO-UMC causality assessment', 'pv_signal'),
      t('pv_control_loop_tick', 'PV control loop tick', 'pv_signal'),
      t('pv_pipeline', 'Full PV pipeline execution', 'pv_signal'),
      t('pv_signal_cooperative', 'Cooperative signal detection', 'pv_signal'),
      t('pv_signal_strength', 'Signal strength assessment', 'pv_signal'),
    ],
  },
  {
    domain: 'vigilance', label: 'Vigilance',
    description: 'Safety margin, risk scoring, and harm classification',
    tools: [
      t('vigilance_safety_margin', 'Safety margin calculation', 'vigilance'),
      t('vigilance_risk_score', 'Risk score computation', 'vigilance'),
      t('vigilance_harm_types', 'Harm type classification (A-H)', 'vigilance'),
      t('vigilance_map_to_tov', 'Map to Theory of Vigilance', 'vigilance'),
    ],
  },
  {
    domain: 'faers', label: 'FAERS',
    description: 'FDA Adverse Event Reporting System queries',
    tools: [
      t('faers_search', 'Search FAERS database', 'faers'),
      t('faers_drug_events', 'Drug adverse events', 'faers'),
      t('faers_signal_check', 'Check drug-event signal', 'faers'),
      t('faers_disproportionality', 'Disproportionality analysis', 'faers'),
      t('faers_compare_drugs', 'Compare drug safety profiles', 'faers'),
      t('faers_polypharmacy', 'Polypharmacy interactions', 'faers'),
      t('faers_reporter_weighted', 'Reporter-weighted signals', 'faers'),
      t('faers_outcome_conditioned', 'Outcome-conditioned analysis', 'faers'),
      t('faers_geographic_divergence', 'Geographic divergence', 'faers'),
      t('faers_seriousness_cascade', 'Seriousness cascade', 'faers'),
      t('faers_signal_velocity', 'Signal velocity trend', 'faers'),
    ],
  },
  {
    domain: 'kellnr', label: 'Kellnr Compute',
    description: 'PK, thermodynamics, statistics, graph, decision trees, surveillance',
    tools: [
      t('kellnr_compute_pk_auc', 'Area under the curve', 'kellnr'),
      t('kellnr_compute_pk_steady_state', 'Steady state concentration', 'kellnr'),
      t('kellnr_compute_pk_ionization', 'Ionization fraction', 'kellnr'),
      t('kellnr_compute_pk_clearance', 'Drug clearance', 'kellnr'),
      t('kellnr_compute_pk_volume_distribution', 'Volume of distribution', 'kellnr'),
      t('kellnr_compute_pk_michaelis_menten', 'Michaelis-Menten kinetics', 'kellnr'),
      t('kellnr_compute_thermo_gibbs', 'Gibbs free energy', 'kellnr'),
      t('kellnr_compute_thermo_kd', 'Dissociation constant', 'kellnr'),
      t('kellnr_compute_thermo_binding_affinity', 'Binding affinity', 'kellnr'),
      t('kellnr_compute_thermo_arrhenius', 'Arrhenius equation', 'kellnr'),
      t('kellnr_compute_stats_welch_ttest', 'Welch t-test', 'kellnr'),
      t('kellnr_compute_stats_ols_regression', 'OLS regression', 'kellnr'),
      t('kellnr_compute_stats_poisson_ci', 'Poisson CI', 'kellnr'),
      t('kellnr_compute_stats_bayesian_posterior', 'Bayesian posterior', 'kellnr'),
      t('kellnr_compute_stats_entropy', 'Shannon entropy', 'kellnr'),
      t('kellnr_compute_graph_betweenness', 'Betweenness centrality', 'kellnr'),
      t('kellnr_compute_graph_mutual_info', 'Mutual information', 'kellnr'),
      t('kellnr_compute_graph_tarjan_scc', 'Tarjan SCC', 'kellnr'),
      t('kellnr_compute_graph_topsort', 'Topological sort', 'kellnr'),
      t('kellnr_compute_dtree_feature_importance', 'Feature importance', 'kellnr'),
      t('kellnr_compute_dtree_prune', 'Decision tree pruning', 'kellnr'),
      t('kellnr_compute_dtree_to_rules', 'Tree to rules', 'kellnr'),
      t('kellnr_compute_signal_sprt', 'SPRT sequential test', 'kellnr'),
      t('kellnr_compute_signal_cusum', 'CUSUM detection', 'kellnr'),
      t('kellnr_compute_signal_weibull_tto', 'Weibull time-to-onset', 'kellnr'),
    ],
  },
  {
    domain: 'kellnr_registry', label: 'Kellnr Registry',
    description: 'Crate registry (read-only)',
    tools: [
      t('kellnr_search_crates', 'Search crate registry', 'kellnr_registry'),
      t('kellnr_get_crate_metadata', 'Get crate metadata', 'kellnr_registry'),
      t('kellnr_list_crate_versions', 'List crate versions', 'kellnr_registry'),
      t('kellnr_get_version_details', 'Get version details', 'kellnr_registry'),
      t('kellnr_list_all_crates', 'List all crates', 'kellnr_registry'),
      t('kellnr_get_dependencies', 'Get dependencies', 'kellnr_registry'),
      t('kellnr_get_dependents', 'Get dependents', 'kellnr_registry'),
      t('kellnr_health_check', 'Registry health check', 'kellnr_registry'),
      t('kellnr_registry_stats', 'Registry statistics', 'kellnr_registry'),
    ],
  },
  {
    domain: 'guidelines', label: 'Guidelines & ICH',
    description: 'Regulatory guideline search, ICH, and MeSH terminology',
    tools: [
      t('guidelines_search', 'Search regulatory guidelines', 'guidelines'),
      t('guidelines_get', 'Get specific guideline', 'guidelines'),
      t('guidelines_categories', 'List categories', 'guidelines'),
      t('guidelines_pv_all', 'All PV guidelines', 'guidelines'),
      t('guidelines_url', 'Get guideline URL', 'guidelines'),
      t('ich_lookup', 'ICH guideline lookup', 'guidelines'),
      t('ich_search', 'Search ICH guidelines', 'guidelines'),
      t('ich_guideline', 'ICH guideline details', 'guidelines'),
      t('ich_stats', 'ICH statistics', 'guidelines'),
      t('mesh_search', 'Search MeSH terms', 'guidelines'),
      t('mesh_lookup', 'Look up MeSH term', 'guidelines'),
      t('mesh_tree', 'MeSH tree hierarchy', 'guidelines'),
      t('mesh_crossref', 'MeSH cross-reference', 'guidelines'),
      t('mesh_consistency', 'Term consistency check', 'guidelines'),
      t('mesh_enrich_pubmed', 'Enrich with PubMed', 'guidelines'),
    ],
  },
  {
    domain: 'stem', label: 'STEM',
    description: 'Science, technology, engineering, math computations',
    tools: [
      t('stem_version', 'STEM engine version', 'stem'),
      t('stem_taxonomy', 'STEM taxonomy browser', 'stem'),
      t('stem_confidence_combine', 'Combine confidence values', 'stem'),
      t('stem_tier_info', 'Tier information', 'stem'),
      t('stem_chem_balance', 'Chemical equation balancing', 'stem'),
      t('stem_chem_fraction', 'Chemical fraction', 'stem'),
      t('stem_chem_ratio', 'Chemical ratio', 'stem'),
      t('stem_chem_rate', 'Reaction rate', 'stem'),
      t('stem_chem_affinity', 'Chemical affinity', 'stem'),
      t('stem_phys_fma', 'F=ma force calculation', 'stem'),
      t('stem_phys_conservation', 'Conservation law check', 'stem'),
      t('stem_phys_period', 'Oscillation period', 'stem'),
      t('stem_phys_amplitude', 'Wave amplitude', 'stem'),
      t('stem_phys_scale', 'Physical scaling', 'stem'),
      t('stem_phys_inertia', 'Moment of inertia', 'stem'),
      t('stem_math_bounds_check', 'Bounds verification', 'stem'),
      t('stem_math_relation_invert', 'Relation inversion', 'stem'),
      t('stem_math_proof', 'Proof assistant', 'stem'),
      t('stem_math_identity', 'Identity verification', 'stem'),
      t('stem_spatial_distance', 'Spatial distance', 'stem'),
      t('stem_spatial_triangle', 'Triangle geometry', 'stem'),
      t('stem_spatial_neighborhood', 'Spatial neighborhood', 'stem'),
      t('stem_spatial_dimension', 'Dimensional analysis', 'stem'),
      t('stem_spatial_orientation', 'Spatial orientation', 'stem'),
    ],
  },
  {
    domain: 'chemistry', label: 'Chemistry',
    description: 'Cross-domain chemistry computations',
    tools: [
      t('chemistry_threshold_rate', 'Threshold rate', 'chemistry'),
      t('chemistry_decay_remaining', 'Remaining after decay', 'chemistry'),
      t('chemistry_saturation_rate', 'Saturation rate', 'chemistry'),
      t('chemistry_feasibility', 'Reaction feasibility', 'chemistry'),
      t('chemistry_dependency_rate', 'Dependency rate', 'chemistry'),
      t('chemistry_buffer_capacity', 'Buffer capacity', 'chemistry'),
      t('chemistry_signal_absorbance', 'Signal absorbance', 'chemistry'),
      t('chemistry_equilibrium', 'Equilibrium constant', 'chemistry'),
      t('chemistry_pv_mappings', 'Chemistry-to-PV mappings', 'chemistry'),
      t('chemistry_threshold_exceeded', 'Threshold exceedance', 'chemistry'),
      t('chemistry_hill_response', 'Hill dose-response', 'chemistry'),
      t('chemistry_nernst_potential', 'Nernst potential', 'chemistry'),
      t('chemistry_inhibition_rate', 'Enzyme inhibition rate', 'chemistry'),
      t('chemistry_eyring_rate', 'Eyring rate constant', 'chemistry'),
      t('chemistry_langmuir_coverage', 'Langmuir coverage', 'chemistry'),
      t('chemistry_first_law_closed', 'First law (closed)', 'chemistry'),
      t('chemistry_first_law_open', 'First law (open)', 'chemistry'),
    ],
  },
  {
    domain: 'epidemiology', label: 'Epidemiology',
    description: 'Epidemiological calculations and survival analysis',
    tools: [
      t('epi_relative_risk', 'Relative risk (2x2)', 'epidemiology'),
      t('epi_odds_ratio', 'Odds ratio (2x2)', 'epidemiology'),
      t('epi_attributable_risk', 'Attributable risk', 'epidemiology'),
      t('epi_nnt_nnh', 'NNT / NNH', 'epidemiology'),
      t('epi_attributable_fraction', 'Attributable fraction', 'epidemiology'),
      t('epi_population_af', 'Population AF', 'epidemiology'),
      t('epi_incidence_rate', 'Incidence rate', 'epidemiology'),
      t('epi_prevalence', 'Prevalence estimation', 'epidemiology'),
      t('epi_kaplan_meier', 'Kaplan-Meier survival', 'epidemiology'),
      t('epi_smr', 'Standardized mortality ratio', 'epidemiology'),
      t('epi_pv_mappings', 'Epi-to-PV mappings', 'epidemiology'),
      t('pv_core_kaplan_meier', 'PV Core Kaplan-Meier', 'epidemiology'),
      t('pv_core_log_rank', 'Log-rank test', 'epidemiology'),
      t('pv_core_cumulative_incidence', 'Cumulative incidence', 'epidemiology'),
      t('pv_core_cox', 'Cox proportional hazards', 'epidemiology'),
      t('pv_core_hazard_ratio', 'Hazard ratio', 'epidemiology'),
      t('pv_core_fdr_adjust', 'FDR p-value adjustment', 'epidemiology'),
    ],
  },
  {
    domain: 'edit_distance', label: 'Edit Distance',
    description: 'String edit distance and similarity',
    tools: [
      t('edit_distance_compute', 'Compute edit distance', 'edit_distance'),
      t('edit_distance_similarity', 'Similarity score (0-1)', 'edit_distance'),
      t('edit_distance_traceback', 'Edit operation traceback', 'edit_distance'),
      t('edit_distance_transfer', 'Cross-domain transfer', 'edit_distance'),
      t('edit_distance_batch', 'Batch computation', 'edit_distance'),
    ],
  },
  {
    domain: 'wolfram', label: 'Wolfram',
    description: 'Wolfram Alpha external computation',
    tools: [
      t('wolfram_query', 'Full Wolfram Alpha query', 'wolfram'),
      t('wolfram_short_answer', 'Short factual answer', 'wolfram'),
      t('wolfram_spoken_answer', 'Spoken answer format', 'wolfram'),
      t('wolfram_calculate', 'Mathematical calculation', 'wolfram'),
      t('wolfram_step_by_step', 'Step-by-step solution', 'wolfram'),
      t('wolfram_plot', 'Plot generation', 'wolfram'),
      t('wolfram_convert', 'Unit conversion', 'wolfram'),
      t('wolfram_chemistry', 'Chemistry query', 'wolfram'),
      t('wolfram_physics', 'Physics query', 'wolfram'),
      t('wolfram_astronomy', 'Astronomy query', 'wolfram'),
      t('wolfram_statistics', 'Statistics query', 'wolfram'),
      t('wolfram_data_lookup', 'Data lookup', 'wolfram'),
      t('wolfram_query_with_assumption', 'Query with assumptions', 'wolfram'),
      t('wolfram_query_filtered', 'Filtered query', 'wolfram'),
      t('wolfram_image_result', 'Image result', 'wolfram'),
      t('wolfram_datetime', 'Date/time query', 'wolfram'),
      t('wolfram_nutrition', 'Nutrition data', 'wolfram'),
      t('wolfram_finance', 'Financial data', 'wolfram'),
      t('wolfram_linguistics', 'Linguistics query', 'wolfram'),
    ],
  },
]

export const TOOL_CATALOG: DomainGroup[] = [...CORE_DOMAINS, ...EXTENDED_DOMAINS]
export const TOTAL_TOOLS = TOOL_CATALOG.reduce((sum, g) => sum + g.tools.length, 0)
export const TOTAL_DOMAINS = TOOL_CATALOG.length

export type { ToolDef, DomainGroup, ParamDef } from './types'
