/**
 * Community Analytics Types
 *
 * Types for forum analytics and AI analysis results.
 *
 * @module types/community/analytics
 */

import type { ForumId, PostId, CommunityUserId } from './branded-ids';
import type { FlexibleTimestamp } from './timestamps';
import type {
  AnalyticsPeriod,
  Sentiment,
  ExpertiseLevel,
  AnalysisTargetType,
} from './enums';

// ============================================================================
// ENGAGEMENT METRICS
// ============================================================================

/**
 * Forum engagement metrics.
 */
export interface EngagementMetrics {
  readonly totalPosts: number;
  readonly totalReplies: number;
  readonly totalReactions: number;
  readonly totalViews: number;
  readonly uniqueContributors: number;
  readonly avgResponseTime: number;
}

// ============================================================================
// GROWTH METRICS
// ============================================================================

/**
 * Forum growth metrics.
 */
export interface GrowthMetrics {
  readonly newMembers: number;
  readonly memberChurn: number;
  readonly netGrowth: number;
  readonly growthRate: number;
}

// ============================================================================
// QUALITY METRICS
// ============================================================================

/**
 * Forum quality metrics.
 */
export interface QualityMetrics {
  readonly acceptedAnswerRate: number;
  readonly avgPostQuality: number;
  readonly helpfulReactionRate: number;
}

// ============================================================================
// TRENDING DATA
// ============================================================================

/**
 * Forum trending data.
 */
export interface TrendingData {
  readonly topTopics: readonly string[];
  readonly topContributors: readonly CommunityUserId[];
  readonly hotDiscussions: readonly PostId[];
}

// ============================================================================
// FORUM ANALYTICS
// ============================================================================

/**
 * Forum Analytics
 *
 * Analytics data for a forum.
 *
 * @remarks
 * Computed periodically and stored for dashboard display
 * and trend analysis.
 */
export interface ForumAnalytics {
  readonly forumId: ForumId;
  readonly period: AnalyticsPeriod;
  readonly engagement: EngagementMetrics;
  readonly growth: GrowthMetrics;
  readonly quality: QualityMetrics;
  readonly trending: TrendingData;
  readonly calculatedAt: FlexibleTimestamp;
}

// ============================================================================
// AI ANALYSIS
// ============================================================================

/**
 * AI content analysis results.
 */
export interface ContentAnalysis {
  readonly topics: readonly string[];
  readonly sentiment: Sentiment;
  readonly expertiseLevel: ExpertiseLevel;
  readonly suggestedCategory?: string;
  readonly suggestedTags?: readonly string[];
  readonly qualityScore?: number;
}

/**
 * AI-generated recommendations from analysis.
 */
export interface AnalysisRecommendations {
  readonly similarContent: readonly string[];
  readonly relevantForums: readonly ForumId[];
  readonly suggestedConnections: readonly CommunityUserId[];
}

/**
 * AI Analysis Result
 *
 * Result from AI content analysis.
 *
 * @remarks
 * Generated by Gemini analysis of posts, users, or forums
 * to power intelligent features and recommendations.
 */
export interface AIAnalysisResult {
  readonly targetId: PostId | CommunityUserId | ForumId;
  readonly targetType: AnalysisTargetType;
  readonly analysis: ContentAnalysis;
  readonly recommendations?: AnalysisRecommendations;
  readonly processedAt: FlexibleTimestamp;
  readonly modelVersion: string;
}
