/**
 * Pathway Assembler
 *
 * Auto-assembles the full CapabilityPathway from 8 stage files.
 * Generated by academy-forge compile module.
 * To update content, edit the stage files in ./stages/.
 * To update pathway metadata, edit ./config.ts.
 *
 * @example
 * ```tsx
 * import { pathway } from './index';
 * ```
 */

import type { CapabilityPathway } from '@/types/academy';

import { PATHWAY_CONFIG } from './config';
import { stage01 } from './stages/01-appe-rotation-foundation-building';
import { stage02 } from './stages/02-fellowship-months-1-6-foundation-building';
import { stage03 } from './stages/03-fellowship-months-7-12-core-competency';
import { stage04 } from './stages/04-fellowship-months-13-18-advanced-application';
import { stage05 } from './stages/05-fellowship-months-19-24-integration-mastery';
import { stage06 } from './stages/06-professional-development-years-1-2-level-4-consolidation';
import { stage07 } from './stages/07-professional-development-years-3-5-level-5-emergence';
import { stage08 } from './stages/08-executive-pathway-strategic-pv-leadership';

/**
 * Static pathway type — excludes Firestore runtime fields.
 */
export type StaticPathway = Omit<CapabilityPathway, 'userId' | 'createdAt' | 'updatedAt'>;

/**
 * All stages in order. Add or reorder stages here.
 */
const stages = [
  stage01,
  stage02,
  stage03,
  stage04,
  stage05,
  stage06,
  stage07,
  stage08,
] as const;

/**
 * The complete assembled pathway.
 */
export const pathway: StaticPathway = {
  id: PATHWAY_CONFIG.id,
  title: PATHWAY_CONFIG.title,
  description: PATHWAY_CONFIG.description,
  topic: PATHWAY_CONFIG.topic,
  modules: [...stages],
  status: PATHWAY_CONFIG.status,
  visibility: PATHWAY_CONFIG.visibility,
  qualityScore: PATHWAY_CONFIG.qualityScore,
  domain: PATHWAY_CONFIG.domain,
  targetAudience: PATHWAY_CONFIG.targetAudience,
  difficulty: PATHWAY_CONFIG.difficulty,
  metadata: PATHWAY_CONFIG.metadata,
  instructor: PATHWAY_CONFIG.instructor,
  version: PATHWAY_CONFIG.version,
};

/**
 * Get a specific stage by index (0-based).
 */
export function getStage(index: number) {
  return stages[index];
}

/**
 * Get total activity count across all stages.
 */
export function getTotalActivities(): number {
  return stages.reduce((sum, stage) => sum + stage.lessons.length, 0);
}

/**
 * Get total estimated duration in minutes.
 */
export function getTotalDuration(): number {
  return stages.reduce(
    (sum, stage) =>
      sum + stage.lessons.reduce((s, l) => s + (l.estimatedDuration ?? 0), 0),
    0
  );
}

export { stages, PATHWAY_CONFIG };
