/**
 * Pathway Assembler
 *
 * Auto-assembles the full CapabilityPathway from 8 stage files.
 * Generated by academy-forge compile module.
 * To update content, edit the stage files in ./stages/.
 * To update pathway metadata, edit ./config.ts.
 *
 * @example
 * ```tsx
 * import { pathway } from './index';
 * ```
 */

import type { CapabilityPathway } from '@/types/academy';

import { PATHWAY_CONFIG } from './config';
import { stage01 } from './stages/01-core-epas-1-3-icsr-processing-literature-screening-stakeholder-communication';
import { stage02 } from './stages/02-core-epas-4-6-post-marketing-analysis-signal-detection-regulatory-documents';
import { stage03 } from './stages/03-core-epas-7-10-risk-minimization-cross-functional-investigations-qa-ai-tools';
import { stage04 } from './stages/04-executive-epas-11-13-global-strategy-digital-transformation-team-leadership';
import { stage05 } from './stages/05-executive-epas-14-16-regulatory-influence-pv-science-innovation-enterprise-risk';
import { stage06 } from './stages/06-executive-epas-17-18-leader-development-strategic-partnerships';
import { stage07 } from './stages/07-executive-epas-19-20-public-communication-industry-transformation';
import { stage08 } from './stages/08-capstone-multi-source-entrustment-portfolio-progression-planning';

/**
 * Static pathway type — excludes Firestore runtime fields.
 */
export type StaticPathway = Omit<CapabilityPathway, 'userId' | 'createdAt' | 'updatedAt'>;

/**
 * All stages in order. Add or reorder stages here.
 */
const stages = [
  stage01,
  stage02,
  stage03,
  stage04,
  stage05,
  stage06,
  stage07,
  stage08,
] as const;

/**
 * The complete assembled pathway.
 */
export const pathway: StaticPathway = {
  id: PATHWAY_CONFIG.id,
  title: PATHWAY_CONFIG.title,
  description: PATHWAY_CONFIG.description,
  topic: PATHWAY_CONFIG.topic,
  modules: [...stages],
  status: PATHWAY_CONFIG.status,
  visibility: PATHWAY_CONFIG.visibility,
  qualityScore: PATHWAY_CONFIG.qualityScore,
  domain: PATHWAY_CONFIG.domain,
  targetAudience: PATHWAY_CONFIG.targetAudience,
  difficulty: PATHWAY_CONFIG.difficulty,
  metadata: PATHWAY_CONFIG.metadata,
  instructor: PATHWAY_CONFIG.instructor,
  version: PATHWAY_CONFIG.version,
};

/**
 * Get a specific stage by index (0-based).
 */
export function getStage(index: number) {
  return stages[index];
}

/**
 * Get total activity count across all stages.
 */
export function getTotalActivities(): number {
  return stages.reduce((sum, stage) => sum + stage.lessons.length, 0);
}

/**
 * Get total estimated duration in minutes.
 */
export function getTotalDuration(): number {
  return stages.reduce(
    (sum, stage) =>
      sum + stage.lessons.reduce((s, l) => s + (l.estimatedDuration ?? 0), 0),
    0
  );
}

export { stages, PATHWAY_CONFIG };
