import type { TabGroup } from '../types'

export const FDA_DEVICES_GROUP: TabGroup = {
  id: 'devices',
  label: 'Devices',
  icon: 'Cpu',
  tabs: [
    {
      id: 'device-mdr',
      label: 'MDR Reports',
      description: 'Medical Device Reporting — adverse events for medical devices',
      mcpTool: 'openfda_device_events',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'mdr_report_key',
      titleField: 'mdr_report_key',
      dateField: 'date_received',
      detailView: 'drawer',
      badgeConfig: {
        field: 'event_type',
        variants: {
          Death: { label: 'Death', variant: 'destructive' },
          Injury: { label: 'Injury', variant: 'default' },
          Malfunction: { label: 'Malfunction', variant: 'secondary' },
          Other: { label: 'Other', variant: 'outline' },
        },
      },
      columns: [
        { field: 'mdr_report_key', header: 'MDR Key', width: 'w-36', render: 'text', sortable: true, defaultVisible: true },
        { field: 'event_type', header: 'Event Type', width: 'w-28', render: 'badge', sortable: true, defaultVisible: true },
        { field: 'date_received', header: 'Date Received', width: 'w-32', render: 'date', sortable: true, defaultVisible: true },
        { field: 'device.brand_name', header: 'Device Brand', render: 'truncate', defaultVisible: true },
        { field: 'patient.sequence_number_outcome', header: 'Patient Outcome', render: 'list', defaultVisible: true },
        { field: 'device.manufacturer_d_name', header: 'Manufacturer', render: 'truncate', defaultVisible: false },
        { field: 'device.device_class', header: 'Device Class', width: 'w-28', render: 'badge', defaultVisible: false },
      ],
      filters: [
        {
          id: 'event_type',
          label: 'Event Type',
          type: 'select',
          queryField: 'event_type',
          options: [
            { label: 'Death', value: 'Death' },
            { label: 'Injury', value: 'Injury' },
            { label: 'Malfunction', value: 'Malfunction' },
            { label: 'Other', value: 'Other' },
          ],
        },
        { id: 'date_range', label: 'Date Received', type: 'date-range', queryField: 'date_received' },
      ],
    },
    {
      id: 'device-recalls',
      label: 'Device Recalls',
      description: 'FDA medical device recall enforcement actions',
      mcpTool: 'openfda_device_recalls',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'recall_number',
      titleField: 'recall_number',
      dateField: 'recall_initiation_date',
      detailView: 'drawer',
      badgeConfig: {
        field: 'classification',
        variants: {
          'Class I': { label: 'Class I', variant: 'destructive' },
          'Class II': { label: 'Class II', variant: 'default' },
          'Class III': { label: 'Class III', variant: 'secondary' },
        },
      },
      columns: [
        { field: 'recall_number', header: 'Recall #', width: 'w-36', render: 'text', sortable: true, defaultVisible: true },
        { field: 'classification', header: 'Class', width: 'w-24', render: 'badge', sortable: true, defaultVisible: true },
        { field: 'recalling_firm', header: 'Recalling Firm', render: 'truncate', defaultVisible: true },
        { field: 'reason_for_recall', header: 'Reason', render: 'truncate', defaultVisible: true },
        { field: 'status', header: 'Status', width: 'w-28', render: 'badge', sortable: true, defaultVisible: true },
        { field: 'recall_initiation_date', header: 'Initiated', width: 'w-32', render: 'date', sortable: true, defaultVisible: false },
      ],
      filters: [
        {
          id: 'classification',
          label: 'Classification',
          type: 'select',
          queryField: 'classification',
          options: [
            { label: 'Class I', value: 'Class I' },
            { label: 'Class II', value: 'Class II' },
            { label: 'Class III', value: 'Class III' },
          ],
        },
        {
          id: 'status',
          label: 'Status',
          type: 'select',
          queryField: 'status',
          options: [
            { label: 'Active', value: 'Ongoing' },
            { label: 'Terminated', value: 'Terminated' },
            { label: 'Completed', value: 'Completed' },
          ],
        },
      ],
    },
    {
      id: 'device-510k',
      label: '510(k) Clearances',
      description: 'Premarket notification 510(k) substantial equivalence decisions',
      mcpTool: 'openfda_device_510k',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'k_number',
      titleField: 'device_name',
      dateField: 'decision_date',
      detailView: 'drawer',
      badgeConfig: {
        field: 'decision_code',
        variants: {
          SESE: { label: 'Cleared', variant: 'default' },
          SESP: { label: 'Cleared (Spec)', variant: 'secondary' },
          DENG: { label: 'Denied', variant: 'destructive' },
          DNSE: { label: 'NSE', variant: 'outline' },
        },
      },
      columns: [
        { field: 'k_number', header: '510(k) #', width: 'w-32', render: 'text', sortable: true, defaultVisible: true },
        { field: 'applicant', header: 'Applicant', render: 'truncate', defaultVisible: true },
        { field: 'device_name', header: 'Device Name', render: 'truncate', defaultVisible: true },
        { field: 'decision_date', header: 'Decision Date', width: 'w-32', render: 'date', sortable: true, defaultVisible: true },
        { field: 'decision_description', header: 'Decision', width: 'w-40', render: 'badge', sortable: true, defaultVisible: true },
        { field: 'advisory_committee_description', header: 'Advisory Committee', render: 'text', defaultVisible: false },
      ],
      filters: [
        {
          id: 'decision_code',
          label: 'Decision',
          type: 'select',
          queryField: 'decision_code',
          options: [
            { label: 'Substantially Equivalent', value: 'SESE' },
            { label: 'SE with Special Conditions', value: 'SESP' },
            { label: 'Not Substantially Equivalent', value: 'DNSE' },
          ],
        },
        {
          id: 'advisory_committee',
          label: 'Advisory Committee',
          type: 'select',
          queryField: 'advisory_committee',
          options: [
            { label: 'Cardiovascular', value: 'CV' },
            { label: 'Neurology', value: 'NE' },
            { label: 'Orthopedic', value: 'OR' },
            { label: 'Radiology', value: 'RA' },
            { label: 'General Hospital', value: 'HO' },
          ],
        },
        { id: 'date_range', label: 'Decision Date', type: 'date-range', queryField: 'decision_date' },
      ],
    },
    {
      id: 'device-pma',
      label: 'PMA Approvals',
      description: 'Premarket approval — Class III high-risk device decisions',
      mcpTool: 'openfda_device_pma',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'pma_number',
      titleField: 'trade_name',
      dateField: 'decision_date',
      detailView: 'drawer',
      badgeConfig: {
        field: 'decision_code',
        variants: {
          AP: { label: 'Approved', variant: 'default' },
          TA: { label: 'Tentative', variant: 'secondary' },
          DN: { label: 'Denied', variant: 'destructive' },
        },
      },
      columns: [
        { field: 'pma_number', header: 'PMA #', width: 'w-32', render: 'text', sortable: true, defaultVisible: true },
        { field: 'applicant', header: 'Applicant', render: 'truncate', defaultVisible: true },
        { field: 'trade_name', header: 'Trade Name', render: 'truncate', defaultVisible: true },
        { field: 'decision_date', header: 'Decision Date', width: 'w-32', render: 'date', sortable: true, defaultVisible: true },
        { field: 'decision_code', header: 'Decision', width: 'w-28', render: 'badge', sortable: true, defaultVisible: true },
        { field: 'advisory_committee_description', header: 'Committee', render: 'text', defaultVisible: false },
      ],
      filters: [
        {
          id: 'decision_code',
          label: 'Decision',
          type: 'select',
          queryField: 'decision_code',
          options: [
            { label: 'Approved', value: 'AP' },
            { label: 'Tentative Approval', value: 'TA' },
            { label: 'Denied', value: 'DN' },
          ],
        },
        { id: 'date_range', label: 'Decision Date', type: 'date-range', queryField: 'decision_date' },
      ],
    },
    {
      id: 'device-classification',
      label: 'Classification',
      description: 'FDA device classification database — product codes and device classes',
      mcpTool: 'openfda_device_class',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'product_code',
      titleField: 'device_name',
      dateField: 'implant_flag',
      detailView: 'drawer',
      badgeConfig: {
        field: 'device_class',
        variants: {
          '1': { label: 'Class I', variant: 'secondary' },
          '2': { label: 'Class II', variant: 'default' },
          '3': { label: 'Class III', variant: 'destructive' },
          U: { label: 'Unclassified', variant: 'outline' },
        },
      },
      columns: [
        { field: 'product_code', header: 'Product Code', width: 'w-32', render: 'text', sortable: true, defaultVisible: true },
        { field: 'device_name', header: 'Device Name', render: 'truncate', defaultVisible: true },
        { field: 'device_class', header: 'Class', width: 'w-24', render: 'badge', sortable: true, defaultVisible: true },
        { field: 'medical_specialty_description', header: 'Specialty', render: 'text', defaultVisible: true },
        { field: 'regulation_number', header: 'Regulation', width: 'w-28', render: 'text', defaultVisible: false },
        { field: 'submission_type_id', header: 'Submission Type', width: 'w-32', render: 'badge', defaultVisible: false },
      ],
      filters: [
        {
          id: 'device_class',
          label: 'Device Class',
          type: 'select',
          queryField: 'device_class',
          options: [
            { label: 'Class I', value: '1' },
            { label: 'Class II', value: '2' },
            { label: 'Class III', value: '3' },
            { label: 'Unclassified', value: 'U' },
          ],
        },
        {
          id: 'medical_specialty',
          label: 'Medical Specialty',
          type: 'select',
          queryField: 'medical_specialty',
          options: [
            { label: 'Cardiovascular', value: 'CV' },
            { label: 'Neurology', value: 'NE' },
            { label: 'Orthopedic', value: 'OR' },
            { label: 'Radiology', value: 'RA' },
            { label: 'Microbiology', value: 'MI' },
            { label: 'Ophthalmology', value: 'OP' },
          ],
        },
      ],
    },
    {
      id: 'device-udi',
      label: 'UDI Database',
      description: 'Global Unique Device Identification Database (GUDID)',
      mcpTool: 'openfda_device_udi',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'device_id',
      titleField: 'brand_name',
      dateField: 'publish_date',
      detailView: 'drawer',
      columns: [
        { field: 'device_id', header: 'Device ID', width: 'w-48', render: 'text', sortable: true, defaultVisible: true },
        { field: 'brand_name', header: 'Brand Name', render: 'text', sortable: true, defaultVisible: true },
        { field: 'company_name', header: 'Company', render: 'truncate', defaultVisible: true },
        { field: 'device_description', header: 'Description', render: 'truncate', defaultVisible: true },
        { field: 'device_id_type', header: 'ID Type', width: 'w-24', render: 'badge', defaultVisible: false },
        { field: 'commercial_distribution_status', header: 'Dist. Status', width: 'w-36', render: 'badge', defaultVisible: false },
      ],
      filters: [
        {
          id: 'device_id_type',
          label: 'ID Type',
          type: 'select',
          queryField: 'device_id_type',
          options: [
            { label: 'Primary DI', value: 'Primary' },
            { label: 'Secondary DI', value: 'Secondary' },
          ],
        },
        {
          id: 'commercial_distribution_status',
          label: 'Distribution Status',
          type: 'select',
          queryField: 'commercial_distribution_status',
          options: [
            { label: 'In Commercial Distribution', value: 'In Commercial Distribution' },
            { label: 'Not in Commercial Distribution', value: 'Not In Commercial Distribution' },
          ],
        },
      ],
    },
  ],
}
