import type { TabGroup } from '../types'

export const FDA_GUIDANCE_GROUP: TabGroup = {
  id: 'guidance',
  label: 'Guidance & Regs',
  icon: 'BookOpen',
  tabs: [
    {
      id: 'fda-guidance',
      label: 'FDA Guidance',
      description: 'FDA guidance documents — CDER, CBER, CDRH, CFSAN, CTP',
      mcpTool: 'fda_guidance_search',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'id',
      titleField: 'title',
      dateField: 'issue_date',
      detailView: 'drawer',
      badgeConfig: {
        field: 'status',
        variants: {
          Final: { label: 'Final', variant: 'default' },
          Draft: { label: 'Draft', variant: 'secondary' },
          Withdrawn: { label: 'Withdrawn', variant: 'destructive' },
        },
      },
      columns: [
        { field: 'title', header: 'Title', render: 'truncate', sortable: true, defaultVisible: true },
        { field: 'status', header: 'Status', width: 'w-24', render: 'badge', sortable: true, defaultVisible: true },
        { field: 'centers', header: 'Centers', width: 'w-36', render: 'list', defaultVisible: true },
        { field: 'products', header: 'Products', render: 'list', defaultVisible: true },
        { field: 'issue_date', header: 'Issue Date', width: 'w-32', render: 'date', sortable: true, defaultVisible: true },
        { field: 'open_for_comment', header: 'Open Comment', width: 'w-32', render: 'badge', defaultVisible: false },
      ],
      filters: [
        {
          id: 'center',
          label: 'Center',
          type: 'select',
          queryField: 'centers',
          options: [
            { label: 'CDER', value: 'CDER' },
            { label: 'CBER', value: 'CBER' },
            { label: 'CDRH', value: 'CDRH' },
            { label: 'CFSAN', value: 'CFSAN' },
            { label: 'CTP', value: 'CTP' },
            { label: 'OC', value: 'OC' },
          ],
        },
        {
          id: 'status',
          label: 'Status',
          type: 'select',
          queryField: 'status',
          options: [
            { label: 'Final', value: 'Final' },
            { label: 'Draft', value: 'Draft' },
          ],
        },
        { id: 'open_for_comment', label: 'Open for Comment', type: 'toggle', queryField: 'open_for_comment' },
        { id: 'date_range', label: 'Issue Date', type: 'date-range', queryField: 'issue_date' },
      ],
    },
    {
      id: 'ich-guidelines',
      label: 'ICH / CIOMS / EMA',
      description: 'International guidelines — ICH, CIOMS, EMA harmonisation documents',
      mcpTool: 'guidelines_search',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'id',
      titleField: 'title',
      dateField: 'date',
      detailView: 'drawer',
      badgeConfig: {
        field: 'source',
        variants: {
          ICH: { label: 'ICH', variant: 'default' },
          CIOMS: { label: 'CIOMS', variant: 'secondary' },
          EMA: { label: 'EMA', variant: 'outline' },
          WHO: { label: 'WHO', variant: 'outline' },
        },
      },
      columns: [
        { field: 'id', header: 'ID', width: 'w-28', render: 'text', sortable: true, defaultVisible: true },
        { field: 'title', header: 'Title', render: 'truncate', sortable: true, defaultVisible: true },
        { field: 'source', header: 'Source', width: 'w-24', render: 'badge', sortable: true, defaultVisible: true },
        { field: 'category', header: 'Category', width: 'w-36', render: 'badge', defaultVisible: true },
        { field: 'date', header: 'Date', width: 'w-32', render: 'date', sortable: true, defaultVisible: false },
      ],
      filters: [
        {
          id: 'source',
          label: 'Source',
          type: 'select',
          queryField: 'source',
          options: [
            { label: 'ICH', value: 'ICH' },
            { label: 'CIOMS', value: 'CIOMS' },
            { label: 'EMA', value: 'EMA' },
            { label: 'WHO', value: 'WHO' },
          ],
        },
        {
          id: 'category',
          label: 'Category',
          type: 'select',
          queryField: 'category',
          options: [
            { label: 'Safety', value: 'Safety' },
            { label: 'Efficacy', value: 'Efficacy' },
            { label: 'Quality', value: 'Quality' },
            { label: 'Multidisciplinary', value: 'Multidisciplinary' },
          ],
        },
        { id: 'query', label: 'Search', type: 'text', queryField: 'query' },
      ],
    },
    {
      id: 'signal-analytics',
      label: 'Signal Analytics',
      description: 'Pharmacovigilance signal detection — PRR, ROR, IC, EBGM disproportionality',
      mcpTool: 'faers_drug_events',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'drug',
      titleField: 'drug',
      dateField: 'updated_at',
      detailView: 'drawer',
      badgeConfig: {
        field: 'signal_flag',
        variants: {
          signal: { label: 'Signal', variant: 'destructive' },
          watch: { label: 'Watch', variant: 'default' },
          background: { label: 'Background', variant: 'secondary' },
        },
      },
      columns: [
        { field: 'drug', header: 'Drug', render: 'text', sortable: true, defaultVisible: true },
        { field: 'event', header: 'Event', render: 'text', sortable: true, defaultVisible: true },
        { field: 'case_count', header: 'Cases', width: 'w-24', render: 'text', sortable: true, defaultVisible: true },
        { field: 'prr', header: 'PRR', width: 'w-20', render: 'text', sortable: true, defaultVisible: true },
        { field: 'ror', header: 'ROR', width: 'w-20', render: 'text', sortable: true, defaultVisible: true },
        { field: 'ic', header: 'IC', width: 'w-20', render: 'text', sortable: true, defaultVisible: true },
        { field: 'ebgm', header: 'EBGM', width: 'w-20', render: 'text', sortable: true, defaultVisible: false },
        { field: 'signal_flag', header: 'Signal', width: 'w-28', render: 'badge', sortable: true, defaultVisible: false },
      ],
      filters: [
        { id: 'drug', label: 'Drug', type: 'text', queryField: 'drug' },
        { id: 'event', label: 'Event (PT)', type: 'text', queryField: 'event' },
        {
          id: 'signal_threshold',
          label: 'Signal Threshold',
          type: 'select',
          queryField: 'signal_flag',
          options: [
            { label: 'All', value: '' },
            { label: 'Signals Only', value: 'signal' },
            { label: 'Watch + Signal', value: 'watch' },
          ],
        },
        { id: 'date_range', label: 'Report Date', type: 'date-range', queryField: 'date_range' },
      ],
    },
  ],
}
