import type { TabGroup } from '../types'

export const FDA_DRUGS_GROUP: TabGroup = {
  id: 'drugs',
  label: 'Drugs',
  icon: 'Pill',
  tabs: [
    {
      id: 'drug-adverse-events',
      label: 'Adverse Events',
      description: 'FDA Adverse Event Reporting System (FAERS) — spontaneous safety reports',
      mcpTool: 'openfda_drug_events',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'safetyreportid',
      titleField: 'safetyreportid',
      dateField: 'receiptdate',
      detailView: 'drawer',
      badgeConfig: {
        field: 'serious',
        variants: {
          '1': { label: 'Serious', variant: 'destructive' },
          '2': { label: 'Non-Serious', variant: 'secondary' },
        },
      },
      columns: [
        { field: 'safetyreportid', header: 'Report ID', width: 'w-36', render: 'text', sortable: true, defaultVisible: true },
        { field: 'receiptdate', header: 'Receipt Date', width: 'w-32', render: 'date', sortable: true, defaultVisible: true },
        { field: 'serious', header: 'Serious', width: 'w-24', render: 'badge', sortable: true, defaultVisible: true },
        { field: 'patient.reaction', header: 'Reactions', render: 'list', defaultVisible: true },
        { field: 'patient.drug', header: 'Drugs', render: 'list', defaultVisible: true },
        { field: 'primarysourcecountry', header: 'Country', width: 'w-28', render: 'text', sortable: true, defaultVisible: false },
        { field: 'reporttype', header: 'Report Type', width: 'w-28', render: 'badge', defaultVisible: false },
      ],
      filters: [
        { id: 'serious', label: 'Serious Only', type: 'toggle', queryField: 'serious' },
        { id: 'date_range', label: 'Receipt Date', type: 'date-range', queryField: 'receiptdate' },
        {
          id: 'reporter_country',
          label: 'Reporter Country',
          type: 'select',
          queryField: 'primarysourcecountry',
          options: [
            { label: 'United States', value: 'US' },
            { label: 'United Kingdom', value: 'GB' },
            { label: 'Germany', value: 'DE' },
            { label: 'France', value: 'FR' },
            { label: 'Japan', value: 'JP' },
            { label: 'Canada', value: 'CA' },
          ],
        },
      ],
    },
    {
      id: 'drug-labels',
      label: 'Drug Labels',
      description: 'FDA-approved drug labeling (package inserts, SPL)',
      mcpTool: 'openfda_drug_labels',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'id',
      titleField: 'openfda.brand_name',
      dateField: 'effective_time',
      detailView: 'drawer',
      columns: [
        { field: 'openfda.brand_name', header: 'Brand Name', render: 'text', sortable: true, defaultVisible: true },
        { field: 'openfda.generic_name', header: 'Generic Name', render: 'text', sortable: true, defaultVisible: true },
        { field: 'effective_time', header: 'Effective Date', width: 'w-32', render: 'date', sortable: true, defaultVisible: true },
        { field: 'openfda.route', header: 'Route', width: 'w-32', render: 'list', defaultVisible: true },
        { field: 'openfda.manufacturer_name', header: 'Manufacturer', render: 'truncate', defaultVisible: true },
        { field: 'openfda.product_type', header: 'Product Type', width: 'w-36', render: 'badge', defaultVisible: false },
      ],
      filters: [
        {
          id: 'route',
          label: 'Route',
          type: 'select',
          queryField: 'openfda.route',
          options: [
            { label: 'Oral', value: 'ORAL' },
            { label: 'Intravenous', value: 'INTRAVENOUS' },
            { label: 'Topical', value: 'TOPICAL' },
            { label: 'Subcutaneous', value: 'SUBCUTANEOUS' },
            { label: 'Intramuscular', value: 'INTRAMUSCULAR' },
            { label: 'Inhalation', value: 'RESPIRATORY (INHALATION)' },
          ],
        },
        {
          id: 'product_type',
          label: 'Product Type',
          type: 'select',
          queryField: 'openfda.product_type',
          options: [
            { label: 'Human Prescription', value: 'HUMAN PRESCRIPTION DRUG' },
            { label: 'Human OTC', value: 'HUMAN OTC DRUG' },
            { label: 'Biological', value: 'HUMAN PRESCRIPTION DRUG, BIOLOGICAL' },
          ],
        },
      ],
    },
    {
      id: 'drug-recalls',
      label: 'Drug Recalls',
      description: 'FDA drug recall enforcement actions',
      mcpTool: 'openfda_drug_recalls',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'recall_number',
      titleField: 'recall_number',
      dateField: 'recall_initiation_date',
      detailView: 'drawer',
      badgeConfig: {
        field: 'classification',
        variants: {
          'Class I': { label: 'Class I', variant: 'destructive' },
          'Class II': { label: 'Class II', variant: 'default' },
          'Class III': { label: 'Class III', variant: 'secondary' },
        },
      },
      columns: [
        { field: 'recall_number', header: 'Recall #', width: 'w-36', render: 'text', sortable: true, defaultVisible: true },
        { field: 'classification', header: 'Class', width: 'w-24', render: 'badge', sortable: true, defaultVisible: true },
        { field: 'recalling_firm', header: 'Recalling Firm', render: 'truncate', defaultVisible: true },
        { field: 'reason_for_recall', header: 'Reason', render: 'truncate', defaultVisible: true },
        { field: 'status', header: 'Status', width: 'w-28', render: 'badge', sortable: true, defaultVisible: true },
        { field: 'recall_initiation_date', header: 'Initiated', width: 'w-32', render: 'date', sortable: true, defaultVisible: true },
        { field: 'distribution_pattern', header: 'Distribution', render: 'truncate', defaultVisible: false },
      ],
      filters: [
        {
          id: 'classification',
          label: 'Classification',
          type: 'select',
          queryField: 'classification',
          options: [
            { label: 'Class I', value: 'Class I' },
            { label: 'Class II', value: 'Class II' },
            { label: 'Class III', value: 'Class III' },
          ],
        },
        {
          id: 'status',
          label: 'Status',
          type: 'select',
          queryField: 'status',
          options: [
            { label: 'Active', value: 'Ongoing' },
            { label: 'Terminated', value: 'Terminated' },
            { label: 'Completed', value: 'Completed' },
          ],
        },
        { id: 'date_range', label: 'Initiation Date', type: 'date-range', queryField: 'recall_initiation_date' },
      ],
    },
    {
      id: 'drug-ndc',
      label: 'NDC Directory',
      description: 'National Drug Code directory — all marketed drug products',
      mcpTool: 'openfda_drug_ndc',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'product_ndc',
      titleField: 'brand_name',
      dateField: 'listing_expiration_date',
      detailView: 'drawer',
      columns: [
        { field: 'product_ndc', header: 'NDC', width: 'w-36', render: 'text', sortable: true, defaultVisible: true },
        { field: 'brand_name', header: 'Brand Name', render: 'text', sortable: true, defaultVisible: true },
        { field: 'generic_name', header: 'Generic Name', render: 'text', sortable: true, defaultVisible: true },
        { field: 'dosage_form', header: 'Dosage Form', width: 'w-36', render: 'text', sortable: true, defaultVisible: true },
        { field: 'route', header: 'Route', width: 'w-28', render: 'list', defaultVisible: true },
        { field: 'labeler_name', header: 'Labeler', render: 'truncate', defaultVisible: false },
        { field: 'marketing_status', header: 'Mktg Status', width: 'w-36', render: 'badge', defaultVisible: false },
      ],
      filters: [
        {
          id: 'dosage_form',
          label: 'Dosage Form',
          type: 'select',
          queryField: 'dosage_form',
          options: [
            { label: 'Tablet', value: 'TABLET' },
            { label: 'Capsule', value: 'CAPSULE' },
            { label: 'Solution', value: 'SOLUTION' },
            { label: 'Injection', value: 'INJECTION' },
            { label: 'Cream', value: 'CREAM' },
            { label: 'Ointment', value: 'OINTMENT' },
          ],
        },
        {
          id: 'marketing_status',
          label: 'Marketing Status',
          type: 'select',
          queryField: 'marketing_status',
          options: [
            { label: 'Prescription', value: 'Prescription' },
            { label: 'OTC', value: 'OTC' },
            { label: 'Discontinued', value: 'Discontinued' },
          ],
        },
      ],
    },
    {
      id: 'drug-approvals',
      label: 'Approvals',
      description: 'Drugs@FDA — NDA/BLA approval history',
      mcpTool: 'openfda_drugs_at_fda',
      defaultParams: { limit: 25, skip: 0 },
      primaryKey: 'application_number',
      titleField: 'brand_name',
      dateField: 'submissions.submission_status_date',
      detailView: 'drawer',
      badgeConfig: {
        field: 'submissions.submission_status',
        variants: {
          AP: { label: 'Approved', variant: 'default' },
          TA: { label: 'Tentative', variant: 'outline' },
          RJ: { label: 'Rejected', variant: 'destructive' },
        },
      },
      columns: [
        { field: 'application_number', header: 'Application #', width: 'w-36', render: 'text', sortable: true, defaultVisible: true },
        { field: 'sponsor_name', header: 'Sponsor', render: 'truncate', defaultVisible: true },
        { field: 'openfda.brand_name', header: 'Brand Name', render: 'text', sortable: true, defaultVisible: true },
        { field: 'openfda.generic_name', header: 'Generic Name', render: 'text', sortable: true, defaultVisible: true },
        { field: 'submissions.submission_status', header: 'Status', width: 'w-28', render: 'badge', sortable: true, defaultVisible: true },
        { field: 'submissions.submission_status_date', header: 'Status Date', width: 'w-32', render: 'date', sortable: true, defaultVisible: false },
      ],
      filters: [
        {
          id: 'application_type',
          label: 'Application Type',
          type: 'select',
          queryField: 'application_number',
          options: [
            { label: 'NDA', value: 'NDA' },
            { label: 'BLA', value: 'BLA' },
            { label: 'ANDA', value: 'ANDA' },
          ],
        },
        {
          id: 'status',
          label: 'Status',
          type: 'select',
          queryField: 'submissions.submission_status',
          options: [
            { label: 'Approved', value: 'AP' },
            { label: 'Tentative Approval', value: 'TA' },
          ],
        },
      ],
    },
  ],
}
