import {
  Activity, Search, AlertTriangle, Shield, FileText, Terminal,
  BarChart3, LayoutDashboard, ClipboardList, Eye, FileBarChart,
  Cpu, BookOpen, Pill, FileCheck, Gauge, Scale, ShieldCheck,
  Wrench, Brain, Code2, Bug, Network, Database, Waypoints,
  Store, FlaskConical, Beaker, Atom, Microscope, Workflow,
  type LucideIcon,
} from 'lucide-react';

export interface OSTool {
  id: string;
  title: string;
  description: string;
  href: string;
  icon: LucideIcon;
  domain: OSDomain;
  color: string;
  tier: 'explorer' | 'accelerator' | 'enterprise';
  backendEndpoint?: string;
  tags: string[];
}

export type OSDomain =
  | 'vigilance'
  | 'guardian'
  | 'engineering'
  | 'foundation'
  | 'science';

export interface OSDomainMeta {
  label: string;
  description: string;
  color: string;
  borderColor: string;
  bgColor: string;
  icon: LucideIcon;
}

export const DOMAIN_META: Record<OSDomain, OSDomainMeta> = {
  vigilance: {
    label: 'Vigilance',
    description: 'Signal detection, causality, ICSR, and safety classification',
    color: 'text-red-400',
    borderColor: 'border-red-500/30',
    bgColor: 'bg-red-500/5',
    icon: Activity,
  },
  guardian: {
    label: 'Guardian',
    description: 'Homeostasis monitoring, threat assessment, and system health',
    color: 'text-emerald-400',
    borderColor: 'border-emerald-500/30',
    bgColor: 'bg-emerald-500/5',
    icon: ShieldCheck,
  },
  engineering: {
    label: 'Engineering Studio',
    description: 'Code generation, debugging, performance analysis, and architecture',
    color: 'text-cyan-400',
    borderColor: 'border-cyan-500/30',
    bgColor: 'bg-cyan-500/5',
    icon: Wrench,
  },
  foundation: {
    label: 'Foundation',
    description: 'Algorithms, data structures, and computational primitives',
    color: 'text-amber-400',
    borderColor: 'border-amber-500/30',
    bgColor: 'bg-amber-500/5',
    icon: Atom,
  },
  science: {
    label: 'Science & Research',
    description: 'Chemistry models, STEM computations, and cross-domain transfer',
    color: 'text-violet-400',
    borderColor: 'border-violet-500/30',
    bgColor: 'bg-violet-500/5',
    icon: Microscope,
  },
};

export const OS_TOOLS: OSTool[] = [
  // ── Vigilance Domain (17 tools) ──
  {
    id: 'vigilance-dashboard',
    title: 'Dashboard',
    description: 'System health, Guardian homeostasis status, and operational metrics',
    href: '/nucleus/vigilance/dashboard',
    icon: LayoutDashboard,
    domain: 'vigilance',
    color: 'text-emerald-400',
    tier: 'explorer',
    backendEndpoint: '/api/v1/guardian/status',
    tags: ['dashboard', 'health', 'metrics', 'status'],
  },
  {
    id: 'signal-detection',
    title: 'Signal Detection',
    description: 'PRR, ROR, IC, EBGM, Chi-square from 2x2 contingency tables',
    href: '/nucleus/vigilance/signals',
    icon: Activity,
    domain: 'vigilance',
    color: 'text-red-400',
    tier: 'explorer',
    backendEndpoint: '/api/v1/pv/signal/complete',
    tags: ['signal', 'prr', 'ror', 'ic', 'ebgm', 'disproportionality', 'contingency'],
  },
  {
    id: 'faers-explorer',
    title: 'FAERS Signal Explorer',
    description: 'Full FAERS drug search with 5-algorithm signal detection on every drug-event pair',
    href: '/nucleus/vigilance/faers',
    icon: Eye,
    domain: 'vigilance',
    color: 'text-amber-400',
    tier: 'explorer',
    backendEndpoint: '/api/v1/faers/search',
    tags: ['faers', 'fda', 'adverse events', 'drug safety', 'search'],
  },
  {
    id: 'signal-analytics',
    title: 'Signal Analytics',
    description: 'Signal velocity, geographic divergence, seriousness cascade, and reporter-weighted analysis',
    href: '/nucleus/vigilance/analytics',
    icon: BarChart3,
    domain: 'vigilance',
    color: 'text-amber-400',
    tier: 'accelerator',
    tags: ['analytics', 'trends', 'velocity', 'geographic'],
  },
  {
    id: 'icsr-management',
    title: 'ICSR Case Management',
    description: 'E2B(R3) structured cases with causality, seriousness, and submission tracking',
    href: '/nucleus/vigilance/icsr',
    icon: ClipboardList,
    domain: 'vigilance',
    color: 'text-cyan-400',
    tier: 'accelerator',
    tags: ['icsr', 'e2b', 'case', 'reporting', 'submission'],
  },
  {
    id: 'causality-assessment',
    title: 'Causality Assessment',
    description: 'Naranjo Algorithm and WHO-UMC system for drug-event causal relationships',
    href: '/nucleus/vigilance/causality',
    icon: Search,
    domain: 'vigilance',
    color: 'text-cyan-400',
    tier: 'explorer',
    backendEndpoint: '/api/v1/pv/naranjo',
    tags: ['causality', 'naranjo', 'who-umc', 'causal'],
  },
  {
    id: 'drug-safety',
    title: 'Drug Safety Intelligence',
    description: 'Search FDA FAERS for adverse event reports and safety signals by drug name',
    href: '/nucleus/vigilance/drug-safety',
    icon: Shield,
    domain: 'vigilance',
    color: 'text-gold',
    tier: 'explorer',
    backendEndpoint: '/api/v1/faers/drug-events',
    tags: ['drug', 'safety', 'adverse events', 'fda'],
  },
  {
    id: 'seriousness',
    title: 'Seriousness Classification',
    description: 'ICH E2A criteria — expedited reporting threshold determination',
    href: '/nucleus/vigilance/seriousness',
    icon: AlertTriangle,
    domain: 'vigilance',
    color: 'text-red-400',
    tier: 'explorer',
    tags: ['seriousness', 'ich', 'e2a', 'expedited', 'classification'],
  },
  {
    id: 'severity',
    title: 'Severity Assessment',
    description: 'Grade event intensity (mild/moderate/severe) — independent from seriousness per ICH E2A',
    href: '/nucleus/vigilance/severity',
    icon: Gauge,
    domain: 'vigilance',
    color: 'text-yellow-400',
    tier: 'explorer',
    tags: ['severity', 'mild', 'moderate', 'severe', 'grading'],
  },
  {
    id: 'expectedness',
    title: 'Expectedness Classifier',
    description: 'Listed vs unlisted adverse events against reference safety information (SmPC/USPI)',
    href: '/nucleus/vigilance/expectedness',
    icon: FileCheck,
    domain: 'vigilance',
    color: 'text-gold',
    tier: 'explorer',
    tags: ['expectedness', 'listed', 'unlisted', 'smpc', 'uspi'],
  },
  {
    id: 'terminology',
    title: 'Terminology Browser',
    description: 'MedDRA hierarchy — SOC, HLGT, HLT, PT, LLT with cross-terminology mappings',
    href: '/nucleus/vigilance/terminology',
    icon: BookOpen,
    domain: 'vigilance',
    color: 'text-cyan-400',
    tier: 'explorer',
    tags: ['meddra', 'terminology', 'soc', 'pt', 'llt', 'mesh', 'snomed'],
  },
  {
    id: 'drug-resolver',
    title: 'Drug Name Resolver',
    description: 'Resolve trade names to INN (active substance) for aggregation consistency',
    href: '/nucleus/vigilance/drug-resolver',
    icon: Pill,
    domain: 'vigilance',
    color: 'text-gold',
    tier: 'explorer',
    tags: ['drug', 'inn', 'trade name', 'resolver', 'who drug dictionary'],
  },
  {
    id: 'guidelines',
    title: 'Regulatory Guidelines',
    description: 'Search ICH, CIOMS, EMA, FDA, WHO pharmacovigilance guidelines — 894+ indexed terms',
    href: '/nucleus/vigilance/guidelines',
    icon: Scale,
    domain: 'vigilance',
    color: 'text-blue-400',
    tier: 'explorer',
    backendEndpoint: '/api/v1/guidelines/search',
    tags: ['guidelines', 'ich', 'cioms', 'ema', 'fda', 'who', 'regulatory'],
  },
  {
    id: 'qbri',
    title: 'QBRI Assessment',
    description: 'Quantitative benefit-risk index calculator with weighted scoring',
    href: '/nucleus/vigilance/qbri',
    icon: FileText,
    domain: 'vigilance',
    color: 'text-emerald-400',
    tier: 'accelerator',
    tags: ['qbri', 'benefit-risk', 'quantitative', 'assessment'],
  },
  {
    id: 'reporting',
    title: 'Safety Reporting',
    description: 'Signal summaries, audit trails, and Guardian performance reports',
    href: '/nucleus/vigilance/reporting',
    icon: FileBarChart,
    domain: 'vigilance',
    color: 'text-emerald-400',
    tier: 'accelerator',
    tags: ['reporting', 'audit', 'summary', 'performance'],
  },
  {
    id: 'telemetry',
    title: 'Biological Telemetry',
    description: 'Real-time health across 8 biological crates — cytokine, hormones, immunity, energy',
    href: '/nucleus/vigilance/telemetry',
    icon: Cpu,
    domain: 'vigilance',
    color: 'text-cyan-400',
    tier: 'accelerator',
    backendEndpoint: '/api/v1/telemetry',
    tags: ['telemetry', 'biological', 'cytokine', 'hormones', 'health'],
  },
  {
    id: 'pvdsl',
    title: 'PVDSL Editor',
    description: 'Execute pharmacovigilance DSL programs against the NexCore computation engine',
    href: '/nucleus/vigilance/pvdsl',
    icon: Terminal,
    domain: 'vigilance',
    color: 'text-cyan-400',
    tier: 'accelerator',
    backendEndpoint: '/api/v1/pvdsl/execute',
    tags: ['pvdsl', 'dsl', 'editor', 'compiler', 'execute'],
  },

  // ── Guardian Domain (1 tool — dashboard with sub-features) ──
  {
    id: 'guardian-dashboard',
    title: 'Guardian Control Center',
    description: 'Signal detection, FAERS search, homeostasis monitoring, and threat assessment',
    href: '/nucleus/guardian',
    icon: ShieldCheck,
    domain: 'guardian',
    color: 'text-emerald-400',
    tier: 'explorer',
    backendEndpoint: '/api/v1/guardian/status',
    tags: ['guardian', 'homeostasis', 'threat', 'health', 'control'],
  },

  // ── Engineering Studio (10 tools) ──
  {
    id: 'code-gen',
    title: 'Code Generator',
    description: 'Automated Rust boilerplate, API clients, and PVDSL logic generation',
    href: '/nucleus/tools/code-gen',
    icon: Code2,
    domain: 'engineering',
    color: 'text-amber-400',
    tier: 'accelerator',
    tags: ['code', 'generation', 'rust', 'boilerplate', 'api'],
  },
  {
    id: 'debug-assistant',
    title: 'Debug Assistant',
    description: 'AI-powered stack trace analysis, log parsing, and logical anomaly detection',
    href: '/nucleus/tools/debug',
    icon: Bug,
    domain: 'engineering',
    color: 'text-red-400',
    tier: 'accelerator',
    tags: ['debug', 'stack trace', 'error', 'logs', 'analysis'],
  },
  {
    id: 'perf-analyzer',
    title: 'Performance Analyzer',
    description: 'Async workflow optimization and high-throughput data pipeline analysis',
    href: '/nucleus/tools/perf',
    icon: Gauge,
    domain: 'engineering',
    color: 'text-emerald-400',
    tier: 'accelerator',
    tags: ['performance', 'optimization', 'async', 'throughput'],
  },
  {
    id: 'brain-viewer',
    title: 'Brain Storage',
    description: 'Working memory, persistent artifacts, and AI session history',
    href: '/nucleus/tools/brain',
    icon: Brain,
    domain: 'engineering',
    color: 'text-amber-300',
    tier: 'accelerator',
    backendEndpoint: '/api/v1/brain/sessions',
    tags: ['brain', 'memory', 'artifacts', 'sessions'],
  },
  {
    id: 'api-explorer',
    title: 'API Explorer',
    description: 'Interactive NexCore API documentation and endpoint testing',
    href: '/nucleus/tools/api-explorer',
    icon: Terminal,
    domain: 'engineering',
    color: 'text-cyan-400',
    tier: 'explorer',
    tags: ['api', 'explorer', 'documentation', 'testing', 'rest'],
  },
  {
    id: 'visualizer',
    title: 'Architecture Visualizer',
    description: 'Decompose system designs into Lex Primitiva — the 16 fundamental symbols',
    href: '/nucleus/tools/visualizer',
    icon: Network,
    domain: 'engineering',
    color: 'text-violet-400',
    tier: 'accelerator',
    tags: ['architecture', 'lex primitiva', 'primitives', 'visualization', 'decompose'],
  },
  {
    id: 'forge',
    title: 'Primitive Forge',
    description: 'Game-theory roguelike — collect T1 symbols, neutralize antipatterns, forge code',
    href: '/nucleus/forge',
    icon: FlaskConical,
    domain: 'engineering',
    color: 'text-amber-500',
    tier: 'explorer',
    tags: ['forge', 'game', 'primitives', 'roguelike', 'symbols'],
  },
  {
    id: 'registry-hud',
    title: 'Registry HUD',
    description: 'Monitor Kellnr crate registry — 164 crates at crates.nexvigilant.com',
    href: '/nucleus/tools/registry',
    icon: Database,
    domain: 'engineering',
    color: 'text-slate-400',
    tier: 'accelerator',
    tags: ['registry', 'kellnr', 'crates', 'packages'],
  },
  {
    id: 'mesh',
    title: 'Ecosystem Mesh',
    description: 'Full node-to-node navigation graph across all domains and app surfaces',
    href: '/nucleus/tools/mesh',
    icon: Waypoints,
    domain: 'engineering',
    color: 'text-cyan-200',
    tier: 'accelerator',
    tags: ['mesh', 'graph', 'navigation', 'ecosystem'],
  },
  {
    id: 'app-store',
    title: 'App Store',
    description: 'Browse and install ecosystem applications directly in Nucleus',
    href: '/nucleus/tools/store',
    icon: Store,
    domain: 'engineering',
    color: 'text-cyan-300',
    tier: 'explorer',
    tags: ['store', 'apps', 'marketplace', 'install'],
  },

  // ── Foundation (computation tools — new UIs) ──
  {
    id: 'foundation-algorithms',
    title: 'Algorithm Lab',
    description: 'Levenshtein distance, fuzzy search, SHA-256, topological sort, and concept grep',
    href: '/nucleus/tools/api-explorer?domain=foundation',
    icon: Atom,
    domain: 'foundation',
    color: 'text-amber-400',
    tier: 'explorer',
    backendEndpoint: '/api/v1/foundation/levenshtein',
    tags: ['levenshtein', 'fuzzy', 'sha256', 'topsort', 'algorithm'],
  },
  {
    id: 'lex-primitiva',
    title: 'Lex Primitiva',
    description: '16 irreducible universal symbols — decompose any concept to its T1 primitives',
    href: '/nucleus/tools/visualizer',
    icon: Workflow,
    domain: 'foundation',
    color: 'text-violet-400',
    tier: 'explorer',
    tags: ['primitives', 'lex primitiva', 't1', 'decompose', 'composition'],
  },

  // ── Science (cross-domain transfer) ──
  {
    id: 'chemistry-pv',
    title: 'Chemistry-PV Transfer',
    description: 'Arrhenius, Michaelis-Menten, Gibbs — chemistry equations mapped to PV concepts',
    href: '/nucleus/tools/chemistry',
    icon: Beaker,
    domain: 'science',
    color: 'text-violet-400',
    tier: 'accelerator',
    tags: ['chemistry', 'arrhenius', 'michaelis-menten', 'gibbs', 'cross-domain'],
  },
];

export const TOOL_COUNT = OS_TOOLS.length;
export const DOMAIN_COUNT = Object.keys(DOMAIN_META).length;
