/**
 * Academy Pathway Registry
 *
 * Central registry of all compiled academy pathways.
 * Each pathway was generated by academy-forge compile from pathway JSON sources.
 *
 * Usage:
 * ```tsx
 * import { allPathways, getPathwayById, getAllSeedData } from '@/data/pathway-registry';
 * ```
 */

import type { StaticPathway } from '@/data/tov-academy/index';

import { pathway as tovPathway } from '@/data/tov-academy/index';
import { pathway as pvEd01 } from '@/data/pv-ed-01/index';
import { pathway as pvEd02 } from '@/data/pv-ed-02/index';
import { pathway as pvEd03 } from '@/data/pv-ed-03/index';
import { pathway as pvEd04 } from '@/data/pv-ed-04/index';
import { pathway as pvEd05 } from '@/data/pv-ed-05/index';
import { pathway as pvEd06 } from '@/data/pv-ed-06/index';
import { pathway as pvEd07 } from '@/data/pv-ed-07/index';
import { pathway as pvEd08 } from '@/data/pv-ed-08/index';

import { tovSeedData as tovSeed } from '@/data/tov-academy/seed';
import { seedData as pvEd01Seed } from '@/data/pv-ed-01/seed';
import { seedData as pvEd02Seed } from '@/data/pv-ed-02/seed';
import { seedData as pvEd03Seed } from '@/data/pv-ed-03/seed';
import { seedData as pvEd04Seed } from '@/data/pv-ed-04/seed';
import { seedData as pvEd05Seed } from '@/data/pv-ed-05/seed';
import { seedData as pvEd06Seed } from '@/data/pv-ed-06/seed';
import { seedData as pvEd07Seed } from '@/data/pv-ed-07/seed';
import { seedData as pvEd08Seed } from '@/data/pv-ed-08/seed';

/**
 * All compiled pathways in presentation order.
 */
export const allPathways: StaticPathway[] = [
  tovPathway,
  pvEd01,
  pvEd02,
  pvEd03,
  pvEd04,
  pvEd05,
  pvEd06,
  pvEd07,
  pvEd08,
];

/**
 * All seed data for Firestore upload.
 */
export const allSeedData = [
  tovSeed,
  pvEd01Seed,
  pvEd02Seed,
  pvEd03Seed,
  pvEd04Seed,
  pvEd05Seed,
  pvEd06Seed,
  pvEd07Seed,
  pvEd08Seed,
];

/**
 * Look up a pathway by ID.
 */
export function getPathwayById(id: string): StaticPathway | undefined {
  return allPathways.find((p) => p.id === id);
}

/**
 * Get all pathway IDs.
 */
export function getPathwayIds(): string[] {
  return allPathways.map((p) => p.id);
}

/**
 * Get pathway count and total stage/activity stats.
 */
export function getRegistryStats() {
  const totalStages = allPathways.reduce((sum, p) => sum + p.modules.length, 0);
  const totalActivities = allPathways.reduce(
    (sum, p) =>
      sum + p.modules.reduce((s, m) => s + m.lessons.length, 0),
    0
  );

  return {
    pathwayCount: allPathways.length,
    totalStages,
    totalActivities,
    pathways: allPathways.map((p) => ({
      id: p.id,
      title: p.title,
      stages: p.modules.length,
      activities: p.modules.reduce((s, m) => s + m.lessons.length, 0),
      domain: p.domain,
      status: p.status,
    })),
  };
}
